### ISSUE TITLE
[Feature] 프론트엔드 축제 사이트의 초기 환경을 구축한다.

### ISSUE THREAD

**Issue by sayyyho** [LikeLion-at-DGU/2024_fall_festival_front#1]
## ✔️ Issue
- 가을 축제사이트 프론트엔드의 초기 환경을 구축합니다.

## 📝 To-do

- [x] 가을 축제사이트 CI/CD 구축
- [x] 가을 축제사이트 모바일 뷰 구현
- [x] 가을 축제사이트 공통 컴포넌트 UI 구현

## 🛠 Working time

- 1d
