### ISSUE TITLE
[Feature] 공연페이지 - 현재 진행중인 공연 구현 

### ISSUE THREAD

**Issue by nicerjs23** [LikeLion-at-DGU/2024_fall_festival_front#11]
## ✔️ Issue

현재 진행중인 공연 부분 구현  

## 📝 To-do

- [x] 날짜 컴포넌트 구현 
- [x] 공연 슬라이드 구현 
- [x] 축제 열기 컴포넌트 구현

## 🛠 Working time

4D
